### ISSUE TITLE
Fitur Registrasi

### ISSUE THREAD

**Issue by Fnrzz** [Fnrzz/e-learning-fosti#1]
Silahkan buat fitur registrasi biasa. caranya banyak diinternet buat semudah mungkin bisa gunain best pratice. buat nya bisa taruh dicontroller auth ( yang bukan didalam folder api ). nanti view nya bisa di folder auth juga. tinggal samain kayak view login.

**Comment by AdonNeet** [comment]
Do not close this

**Comment by Fnrzz** [comment]
> Do not close this

okee bar udah tak buka

**Comment by Josumaru** [comment]
@Fnrzz I just created a user registration, can you review it?

**Comment by Fnrzz** [comment]
> @Fnrzz I just created a user registration, can you review it?
okee waitt

**Comment by Fnrzz** [comment]
> @Fnrzz I just created a user registration, can you review it?

bisaa di pull request ke branch develop yaaa tak liat udah bagus. sipp

**Comment by Josumaru** [comment]
Ok

**Comment by Josumaru** [comment]
> > @Fnrzz I just created a user registration, can you review it?
> 
> bisaa di pull request ke branch develop yaaa tak liat udah bagus. sipp

ok
